language: python
python:
- '3.4'
install:
- pip install .
- pip install unittest2
script:
- echo "No tests"
before_deploy:
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb
  -O $TRAVIS_BUILD_DIR/pandoc.deb
- sudo dpkg -i $TRAVIS_BUILD_DIR/pandoc.deb
- rm $TRAVIS_BUILD_DIR/pandoc.deb
- pandoc --from=markdown --to=rst --output=$TRAVIS_BUILD_DIR/README.rst README.md
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: "GSWcDIWk8AqurJ/SNn8yCiFKq2TU79wsI7RXpp7lM0qyM8CBt3iza9KzeH4kDsa6DNqvIFZ+IvTsTwrVOCB0gGlFhffrbht+PeEeNVjU1r44YG873bZoWElVhTM5OnOpZPM7vD6TNLQ40xT27OdkPf4uoVjH+dx5M14Gvy1lm3BHkTJJNT2iDNEkgtSthVvDe1Eg6IjtHh8NFRB5juDRhbNavQKSUYOgxPH0k0LSQPvAmcOefIjcF0ZM1qIwm9sqpJHQIzVZuPGf05jIW2wmEPl1/NBSlRJsUivE2G5QHEbHd9Jbdu0/xmpCxMOt8Qo1hfwodieTQDXuRR1WwANHz86rsn00tONW1XtgG6Pg6W9bV5iVI9KHaim2S8sYa8oQzQEbT4hyTvGEWgsklH+id6Nfil8fanqTAf5mkh55qzUULfxbpaJa64TOHhOv6ic/FKPHyhcSPVJCPxs5DtmwJKgQaxLEQc0riIh4kQKo6bW36AVrJJS05KAhV6598EGaE0n1Hra4S5WhE7Odv/ty8WedTh/nHHwTVe6X/Gj6dWuD0kaORXkzNdZIfHu/0gzPRpLKQekKN5P/d+tqSsgSJB9IYCt93YUSa1w4Mz6aSr2G5ITWWB1MmqkVL8RgT4Kv1kDHpBJH0WqtrzGgjxFRPyprQr2KbhYXA8LY90QNozs="
  name: tornadoql-0.1.5
  tag_name: 0.1.5
  on:
    repo: deep-compute/tornadoql
- provider: pypi
  distributions: "sdist bdist_wheel"
  server: https://testpypi.python.org/pypi
  skip_cleanup: true
  user: "deepcompute"
  password:
    secure: "R9mFubnB+scg06Oom8q4PH1/npTbwPP03IDB+v59s/gEEVzgxsiFDlu/H4eEBCQUrNxV7DKmxAzk+95gcjXAVwC/HdafZY04gmvS6vbCSAYU6tX3TgprK0lADFF3MKztUHGUFbY2LHJW4luoSbGjnyp3pyoowIZKE5IDTwE3FCusltOI5Igpp/7Bwxurgc7MKTPARVFXrr3H2X+NaxJjti7gJfRIrAprqYRScLkcHj7O8tJy94I7KbKx02FQ0fpXMyKgd1seiw9BJGRVZSyiW7bjazgEprlhpbepvZMLCstY51f5MrGbDYf5W3G4tHge+rhn3LmYSGy1RPFaGi0ic1oZFYGBOReoupAZaTQtOtkWa9Kj3ifTaRm259G5hcrv5T0JB22HZB8xIRhfzRZe8rdl3XVoj7VUayqVGeOKmNrtQOQV4alDhLJCLO1Y35UoYczIxC5hkstUfA3UINa4sAJSGzNoZR8sF/57wv7vNu2MNQau/SuaxNijhaYzjg49t8557pJPJ3gH+g6ac3/xlqdshbWdmyACx2VsAz7I/iWswt4pHPAzc9GGpuZ+4IDQdTzMI4GBtuqoAKwtK3zvOMBFaGRrEDpfqKIQbiJhkDhk7OJLsTTE9nIsyZEVCR5XAr0b91eUWUzCtQBq8a1Lgt+frJjm08W6hZT79PuNvrc="
  on:
    branch: master
    tags: false
  # pypi
- provider: pypi
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  user: "deepcompute"
  password: 
    secure: "R9mFubnB+scg06Oom8q4PH1/npTbwPP03IDB+v59s/gEEVzgxsiFDlu/H4eEBCQUrNxV7DKmxAzk+95gcjXAVwC/HdafZY04gmvS6vbCSAYU6tX3TgprK0lADFF3MKztUHGUFbY2LHJW4luoSbGjnyp3pyoowIZKE5IDTwE3FCusltOI5Igpp/7Bwxurgc7MKTPARVFXrr3H2X+NaxJjti7gJfRIrAprqYRScLkcHj7O8tJy94I7KbKx02FQ0fpXMyKgd1seiw9BJGRVZSyiW7bjazgEprlhpbepvZMLCstY51f5MrGbDYf5W3G4tHge+rhn3LmYSGy1RPFaGi0ic1oZFYGBOReoupAZaTQtOtkWa9Kj3ifTaRm259G5hcrv5T0JB22HZB8xIRhfzRZe8rdl3XVoj7VUayqVGeOKmNrtQOQV4alDhLJCLO1Y35UoYczIxC5hkstUfA3UINa4sAJSGzNoZR8sF/57wv7vNu2MNQau/SuaxNijhaYzjg49t8557pJPJ3gH+g6ac3/xlqdshbWdmyACx2VsAz7I/iWswt4pHPAzc9GGpuZ+4IDQdTzMI4GBtuqoAKwtK3zvOMBFaGRrEDpfqKIQbiJhkDhk7OJLsTTE9nIsyZEVCR5XAr0b91eUWUzCtQBq8a1Lgt+frJjm08W6hZT79PuNvrc="
  on:
    branch: master
    # only when there is a release it will update pypi
    tags: true
