language: python
python:
- '3.4'
install:
- pip install .
- pip install unittest2
script:
- echo "No tests"
before_deploy:
- wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb
  -O $TRAVIS_BUILD_DIR/pandoc.deb
- sudo dpkg -i $TRAVIS_BUILD_DIR/pandoc.deb
- rm $TRAVIS_BUILD_DIR/pandoc.deb
- pandoc --from=markdown --to=rst --output=$TRAVIS_BUILD_DIR/README.rst README.md
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: 
  name: tornadoql-0.1.5
  tag_name: 0.1.5
  on:
    repo: deep-compute/tornadoql
- provider: pypi
  distributions: "sdist bdist_wheel"
  server: https://testpypi.python.org/pypi
  skip_cleanup: true
  user: "deepcompute"
  password:
    secure: 
  on:
    branch: master
    tags: false
  # pypi
- provider: pypi
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  user: "deepcompute"
  password: 
    secure: 
  on:
    branch: master
    # only when there is a release it will update pypi
    tags: true
